LOG_DIR: '/disk/vanishing_data/du541/tensorboard_logs'
TAG: 'training_results_sample'
# TAG: 'the_last_26'

GPUS: 1
BATCHSIZE: 1
STEPS: 1
VAL_CHECK_INTERVAL: 1
LOGGING_INTERVAL: 1
LOG_VIDEO_INTERVAL: 1
N_WORKERS: 1

OPTIMIZER:
  ACCUMULATE_GRAD_BATCHES: 1

PREDICTION:
 N_SAMPLES: 1

#MODEL:
#  ROUTE:
#    ENABLED: True
#  TRANSFORMER:
#    ENABLED: False
#    CHANNELS: 256

EVAL:
  RGB_SUPERVISION: True

RECEPTIVE_FIELD: 0
FUTURE_HORIZON: 0

PRETRAINED:
  PATH: ''
#  CML_MODEL: '6a5cfa2fc6c74db4b1010a88d74cb6ac'
#  CML_MODEL: ''

DATASET:
  # DATAROOT: '/disk/vanishing_data/du541/AnoVox(Sample)/Anovox'
  DATAROOT: '/disk/vanishing_data/du541/carla_dataset_test'

IMAGE:
  CAMERA_POSITION: [1.0, 0.0, 2.0]  # (forward, right, up)