_BASE_: 'mile.yml'

# LOG_DIR: 'tensorboard_logs'
# TAG: 'predict'

GPUS: 1
BATCHSIZE: 1

STEPS: 8
LOGGING_INTERVAL: 1
LOG_VIDEO_INTERVAL: 1
VAL_CHECK_INTERVAL: 1
LIMIT_VAL_BATCHES: 1
N_WORKERS: 0

OPTIMIZER:
  ACCUMULATE_GRAD_BATCHES: 1

VOXEL_SEG:
  ENABLED: False
  DIMENSION: 32
  N_CLASSES: 9
  USE_WEIGHTS: False

LIDAR_RE:
  ENABLED: False

LIDAR_SEG:
  ENABLED: False
  N_CLASSES: 9
  USE_WEIGHTS: False

SEMANTIC_IMAGE:
  ENABLED: False
  N_CLASSES: 9
  USE_WEIGHTS: False

DEPTH:
  ENABLED: False

LOSSES:
  RGB_INSTANCE: False
  SSIM: False

MODEL:
  EMBEDDING_DIM: 512
  # ROUTE: False

EVAL:
  RGB_SUPERVISION: True

RECEPTIVE_FIELD: 6
FUTURE_HORIZON: 6

PRETRAINED:
  PATH: '/disk/vanishing_data/du541/epoch=65-step=99000_.ckpt'

#DATASET:
#  DATAROOT: ''
#  VERSION: 'mini'
